# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e77d4739467e547cacb1d506f940f1b47e9d31de9237c2ac0441155d79dfde4f94d385cde405d04dc4da33851d84c659855ab743108a774dbf21330d6023040

test:
  secret_key_base: cda7d27625a3cfb86cc9937e1a6de87abeec7ce7634f744293f71e4c5626e18e5871ecac65940d29e11917fdd7f30d031b42fc98f2fa4c97d79f849ee048bc77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
